---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: springboot
  labels:
    app: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot-monitor
          image: 'docker.io/dhanyashree/springboot:b3'
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
         
---
kind: Service
apiVersion: v1
metadata:
  name: springboot-svc-monitoring
spec:
  ports:
    - name: 9080-metrics
      protocol: TCP
      port: 9080
      targetPort: 9080
  selector:
    app: springboot
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: test
spec:
  to:
    kind: Service
    name:springboot-svc-monitoring
  port:
    targetPort: 9080-metrics
